# Generated by Django 5.2.9 on 2026-01-30 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_especialidad_alter_incidencia_tecnico_asignado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
    ]
